name: "Reflesh Template"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "28 0 * * 3"

jobs:
  PullAndFix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Pull
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add template https://github.com/UniPro-tech/NextBlogComplateStarter.git
          echo "HASH=$(git rev-parse temolate/HEAD)" >> $GITHUB_ENV
          git branch template/master_${{ env.HASH }}
          git pull template master:template/master_${{ env.HASH }}
  PR:
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: fix/hoge_${{ env.HASH }}
          destination_branch: main
          pr_title: Update template
          pr_label: dependencies
          github_token: ${{ secrets.GITHUB_TOKEN }}
