name: "Reflesh Template"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "28 0 * * 3"

concurrency:
  group: "PullAndFix"
  cancel-in-progress: false

jobs:
  PullAndFix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Remote Add
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git remote add template https://github.com/UniPro-tech/NextBlogComplateStarter.git
      - name: Pull
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch template master:template/master
      - name: Checkout doc
        uses: actions/checkout@v4
        with:
          ref: template/master
          path: template/master
      - name: Delete workflow
        run: |
          rm -r ./.github
      - name: Commit
        run: |
          git config --global user.email "workflow@github.com"
          git config --global user.name "Workflow"
          git commit -a -m "Del workflow"
      - name: Push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: git push -u origin template/master
